### ISSUE TITLE
Cannot wait for async refs

### ISSUE THREAD

**Issue by piotrgolawski** [gk4m/react-use-scroll-sync#12]
Hello,
I am using refs in child components so I need to wait a little for them.
So I am getting an error (I need to use at least two refs), cannot use it in hook, because it is a hook.

How can I solve this?

**Comment by piotrgolawski** [comment]
I manage to create refs first as in example. 
Can be closed.
Thanks for your work!

**Comment by tianchai-emit** [comment]
@piotrgolawski Can you tell me how to achieve that please? I'm in a situation where I have to pass ref to child components and initiate the hook at parent component.
