### ISSUE TITLE
Slow mousewheel scrolling

### ISSUE THREAD

**Issue by nahue** [gk4m/react-use-scroll-sync#3]
Using the mouse wheel in the demo feels choppy. I'm investigating for a fix.. since your hook works perfectly except for that small issue.

Thanks!

**Comment by nahue** [comment]
Maybe only applying scrollTop or scrollLeft to the element that's NOT being scrolled by the user?  🤔

**Comment by gk4m** [comment]
Hey @nahue , thanks for reporting issue. It looks like @sasza2 fixed this problem so I will close the issue.
